name: Feature request
description: Propose a new capability or improvement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea. Please focus on user value and expected behavior.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user pain or limitation are you trying to solve?
      placeholder: As a ..., I want ..., so that ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior, API/UI changes, and constraints.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other options did you consider?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, mockups, or examples from similar tools.
    validations:
      required: false
